### PR TITLE
Show file type in gallery

### PR DESCRIPTION
**Pull request by DontTalkToMeThx**
Shows the file type of each post in the gallery.
vglwr8_18636 1

### CODE REVIEW

**Comment by DontTalkToMeThx** [comment]
I can't run rubocop for some reason. One sec.

**Comment by faucetlol** [comment]
> I can't run rubocop for some reason. One sec.

Is `docker compose run --rm rubocop` not working?

**Comment by DontTalkToMeThx** [comment]
> Is docker compose run --rm rubocop not working?

No, it isn't.

**Comment by faucetlol** [comment]
> I'm also not entirely sure what it wants me to do since, to me, using .to_s here just makes the code less readable lol

I don't think you need the string interpolation here at all, `<%= Marcel::TYPE_EXTS[submission_file.content_type].first.upcase %>` should suffice. I'm not too well versed with Ruby either, but that at least doesn't throw up any issues with Rubocop.

**Comment by DontTalkToMeThx** [comment]
You are completely right

**Pull request merged**
