### PR TITLE
Add a bunch of new simple website definitions

### PR DESCRIPTION
**Pull request by faucetlol2**
Add simple definitions for AfterDark, Artconomy, Art Fight, Boosty, Buzzly, FurryStation, Toyhouse and YCH.art. I've been using these myself for a little while and thought it might actually be a good idea to make a PR for them (especially since I'd end up with conflicting enum problems if you added any more). The username identifier regex may be less than ideal for some, but I think it should be fine.

Eventually I have plans to make scrapers for some of these too, since a lot of them actually seem to be a good source for images.

### CODE REVIEW

**Comment by Earlopain** [comment]
Looks like I need to modify the workflow to work for outside contributors. Can you please run `docker-compose run --rm rubocop` and fix the offences?

**Comment by faucetlol2** [comment]
I forgot about RuboCop, sorry! It should all be fixed now.

I didn't know Ruby allowed for trailing commas, JSON parsers have trained me out of using them 😅

**Comment by Earlopain** [comment]
Thanks! I'm going to take a look into changing the workflow to work for you as well. The problem seems to be that it always uploads to the container registry, and only I have permission for that

**Comment by Earlopain** [comment]
The workflow _should_ be fine now. Man, that was annoying. Maybe try and see if it works sometime (:

**Pull request merged**
