### PR TITLE
Add Omorashi scraper

### PR DESCRIPTION
**Pull request by faucetlol**
Adds a scraper for omorashi.org, it's pretty much fully working but there's one problem I'm stumped with.

https://github.com/Earlopain/reverser/blob/305c37b889939e7e71c40843dec7f6257279b8c5/app/logical/scraper/omorashi.rb#L47-L50

Once the scraper reaches a page that doesn't exist the server responds with a 303 redirect back to the first page, which causes HTTPX to throw an error. I thought I could catch the exception and just return `[]` if the status was `303`, but I couldn't figure out an easy way to check the status of the request's response.

I'm sure I could come up with a hacky solution, but I'd rather some advice how to do it the correct way. I'm probably missing something obvious.

### CODE REVIEW

**Comment by Earlopain** [comment]
The custom `fetch_json`/`fetch_json` methods raise on non 200 range status codes and only return the response body. I've found this to be easier since I've never needed something else, until now at least.

You can just call the normal fetch method directly and forgo that machinery to get a proper httpx response, something like this should work:

```rb
response = scraper.get("your_url")
if response.status == 303
  []
else
  Nokogiri::HTML(response.body.to_s)
end
```

If you need to follow this redirect for some reason you can tell httpx to do this by default by adding the `follow_redirects` plugin. You can look at `extend_client` in the reddit scraper on how to modify the httpx instance for a specific scraper. `scraper` will then use this.

Please do add the site to the readme as well.

**Comment by faucetlol** [comment]
`scraper` is undefined so I'm assuming you mean `client.get()`? That still seems to raise an exception either way. I _could_ always use `HTTPX.get()` but the lack of logging the requests would be less than ideal.

> Please do add this scraper to the readme as well.

My bad. I referenced the steps I took last time I added a website, but that was only a simple definition so it wasn't included on the readme. The test is a pretty smart idea, now I shouldn't forget it in the future.

**Comment by Earlopain** [comment]
Oh yeah, it still goes through the plugin stuff, including raising. I added a commit to master, you can now pass `should_raise: false` when calling `client.get`, see added tests for usage if needed.

**Comment by faucetlol** [comment]
I hope that's good now.

For some reason those checks have just been queued for ages and I got bored of waiting for them, I can't imagine anything's actually wrong with them.

**Comment by Earlopain** [comment]
GitHub is having a bit of a moment right now https://www.githubstatus.com/incidents/wcl1sw4mzg60. I'll merge once this is green.

**Comment by faucetlol** [comment]
Good to know it's nothing I did wrong! I can never remember how to rebase properly whenever it comes to needing to do that.

**Pull request merged**
